DROP DATABASE Science_Center;
CREATE DATABASE Science_Center;
USE Science_Center;

-- --------------------- CREATES------- -------------- --
CREATE TABLE STAFF_MEMBER (
    MEMBER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(100)
);

CREATE TABLE STAFF_MEMBER_EXHIBIT (
    exhibit_admin INT NOT NULL,
    exhibit INT NOT NULL,
    created_at DATETIME
);

CREATE TABLE EXHIBIT (
   EXH_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   EXH_NAME VARCHAR(50) NOT NULL,
   EXH_THEME VARCHAR(40) NOT NULL,
   EXH_DESCR MEDIUMTEXT NOT NULL,
   CREATED_AT DATETIME,
   UPDATED_AT DATETIME
);

CREATE TABLE DIGITAL_SIGN (
     SIGN_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     STATION INT NOT NULL,
     WIDTH INT NOT NULL,
     HEIGHT INT NOT NULL,
     RESOLUTION INT NOT NULL,
     CREATED_AT DATETIME NOT NULL,
     UPDATED_AT DATETIME NOT NULL
);

CREATE TABLE CONTENT_LAYOUT (
      LAYOUT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      LAYOUT_NAME VARCHAR(50) NOT NULL,
      LAYOUT_DESCR VARCHAR(400) NOT NULL,
      MEDIA_PLAYER INT NOT NULL,
      CREATED_AT DATETIME NOT NULL,
      UPDATED_AT DATETIME NOT NULL
);

CREATE TABLE LAYOUT_DEMOGRAPHIC (
    LAYOUT_DEMO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONTENT INT NOT NULL,
    DEMOGRAPHIC INT NOT NULL
);

CREATE TABLE LAYOUT_LANGUAGE (
    LANGUAGE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LANGUAGE_NAME VARCHAR(20)
);

CREATE TABLE DEMOGRAPHIC (
    DEMO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DEMO_NAME VARCHAR(30) NOT NULL,
    DEMO_AGE_FROM INT,
    DEMO_AGE_TO INT,
    DEMO_DESCR VARCHAR(400) NOT NULL
);

CREATE TABLE DISABILITY (
    DISABILITY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DISAB_TYPE VARCHAR(30) NOT NULL,
    DISAB_DESCR VARCHAR(400) NOT NULL
);

CREATE TABLE DEMOGRAPHIC_DISABILITY (
    DEMO_DISAB_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DEMOGRAPHIC INT NOT NULL,
    DISABILITY INT NOT NULL
);

-- -------------- PRIMARY KEY CONSTRAINTS -------------- --
ALTER TABLE STAFF_MEMBER_EXHIBIT
ADD PRIMARY KEY (exhibit_admin, exhibit);

-- -------------- FOREIGN KEY CONSTRAINTS -------------- --
ALTER TABLE DIGITAL_SIGN
ADD FOREIGN KEY (STATION) REFERENCES EXHIBIT(EXH_ID) ON DELETE CASCADE;

ALTER TABLE CONTENT_LAYOUT
ADD FOREIGN KEY (MEDIA_PLAYER) REFERENCES DIGITAL_SIGN(SIGN_ID) ON DELETE CASCADE;

ALTER TABLE LAYOUT_DEMOGRAPHIC
ADD FOREIGN KEY (CONTENT) REFERENCES CONTENT_LAYOUT(LAYOUT_ID) ON DELETE CASCADE;

ALTER TABLE LAYOUT_DEMOGRAPHIC
ADD FOREIGN KEY (DEMOGRAPHIC) REFERENCES DEMOGRAPHIC(DEMO_ID) ON DELETE CASCADE;

ALTER TABLE DEMOGRAPHIC_DISABILITY
ADD FOREIGN KEY (DEMOGRAPHIC) REFERENCES DEMOGRAPHIC(DEMO_ID) ON DELETE CASCADE;

ALTER TABLE DEMOGRAPHIC_DISABILITY
ADD FOREIGN KEY (DISABILITY) REFERENCES DISABILITY(DISABILITY_ID) ON DELETE CASCADE;

ALTER TABLE STAFF_MEMBER_EXHIBIT
ADD FOREIGN KEY (exhibit_admin) REFERENCES STAFF_MEMBER(member_id) ON DELETE CASCADE;

ALTER TABLE STAFF_MEMBER_EXHIBIT
ADD FOREIGN KEY (exhibit) REFERENCES EXHIBIT(EXH_ID) ON DELETE CASCADE;


-- ----------------- INSERTS FOR TESTING ------------------- --

